# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestA():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_a(self):
    self.driver.get("https://publikasi.ojk.go.id/Portal")
    self.driver.set_window_size(1706, 1019)
    self.driver.find_element(By.LINK_TEXT, "Akuntan Publik").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(10) > td:nth-child(10)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(10) > td:nth-child(10)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(10) > td:nth-child(10)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper").click()
  
